[package]
name = "questionmark"
version = "0.1.0"
authors = ["Louis Dureuil <louis.dureuil@xinra.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
